version: '3.8'

services:
#  node-app:
#    build: .
#    image: node-app
#    environment:
#      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
#    ports:
#      - '8085:8085'
#    depends_on:
#      - mongodb
#    volumes:
#      - .:/src
#    networks:
#      - node-network
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network
    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: financeduck

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge